Currently if you don't set up your config.yaml file (or don't set it up correctly) the CLI returns an error like:

    usage: toolkit.py clone [-h]

    HTTPSConnectionPool(host='example.astra.netapp.io', port=443): Max retries exceeded with url: /accounts/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/topology/v1/apps?include=name%2Cid%2CclusterName%2CclusterID%2Cnamespace%2Cstate%2CmanagedState%2CappDefnSource (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8cc9d35310>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

Suggest we change this to:

    Error: Looks like the NetApp Astra Control account information in the config.yaml file is incorrect. Please check the config.yaml file and ensure the information is correct. See the main README file for more information on installing and using this toolkit.

    HTTPSConnectionPool(host='example.astra.netapp.io', port=443): Max retries exceeded with url: /accounts/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/topology/v1/apps?include=name%2Cid%2CclusterName%2CclusterID%2Cnamespace%2Cstate%2CmanagedState%2CappDefnSource (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8cc9d35310>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
